### ISSUE TITLE
dev: Import KML not working

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#83]
Even if I export an existing area as KML and attempt to import it, I get the attached error. Ditto for a series of stored KML files.
![capture](https://cloud.githubusercontent.com/assets/6656350/6590083/36ad594c-c7ff-11e4-9c0f-09121487e205.jpg)

**Comment by adam-collins** [comment]
KML export was broken due to slight change in behaviour of newer lib.

**Comment by adam-collins** [comment]
Fixed on dev.

**Comment by Tasilee** [comment]
Problem remains. One test file was created from KML export. Another worked previously.

**Comment by adam-collins** [comment]
Fixed at least one import problem on dev.

**Comment by Tasilee** [comment]
Looks ok on 5 tests I've run.
